#!/bin/bash

# Docker Host Requirements
# https://github.com/docker-library/docs/tree/master/sonarqube#docker-host-requirements
sysctl -w vm.max_map_count=262144
sysctl -w fs.file-max=65536
ulimit -n 65536
ulimit -u 4096

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/
