#!/bin/bash

# Docker Host Requirements
sysctl -w vm.max_map_count=262144
sysctl -w fs.file-max=65536
ulimit -n 65536
ulimit -u 4096

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

docker build \
    --build-arg TAG=${DOCKER_TAG} \
    --build-arg VCS_REF=`git rev-parse --short HEAD` \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
