#!/bin/bash

# Docker Host Requirements
# https://github.com/docker-library/docs/tree/master/sonarqube#docker-host-requirements
grep vm.max_map_count /etc/sysctl.conf
sudo sed -i -e 's|vm.max_map_count=.*|vm.max_map_count=262144|g' /etc/sysctl.conf
grep vm.max_map_count /etc/sysctl.conf
sudo sysctl -w vm.max_map_count=262144
sudo sysctl -w fs.file-max=65536
sudo ulimit -n 65536
sudo ulimit -u 4096

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/
